# Generated by Django 2.2.3 on 2020-05-04 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Название ru')),
                ('title_en', models.CharField(max_length=200, verbose_name='Название en')),
                ('title_jp', models.CharField(max_length=200, verbose_name='Название jp')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('previous_evolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='pokemon_entities.Pokemon', verbose_name='Из кого эволюционирует')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('appeared_at', models.DateTimeField(verbose_name='Время появления')),
                ('disappeared_at', models.DateTimeField(verbose_name='Время исчезновения')),
                ('level', models.IntegerField(verbose_name='Уровень')),
                ('health', models.IntegerField(verbose_name='Здоровье')),
                ('strength', models.IntegerField(verbose_name='Атака')),
                ('defence', models.IntegerField(verbose_name='Защита')),
                ('stamina', models.IntegerField(verbose_name='Выносливость')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='pokemon_entities.Pokemon', verbose_name='Покемон')),
            ],
        ),
    ]
